export const MAX_MESSAGE_CONTENT_LENGTH = 4000;
export const MAX_REACTION_EMOJI_LENGTH = 32;
export const DEFAULT_MESSAGE_LIST_LIMIT = 50;
export const MAX_MESSAGE_LIST_LIMIT = 100;
export const MAX_MESSAGE_ATTACHMENTS = 10;
