/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDefaultRouteImport } from './routes/_app/_default'
import { Route as AppDefaultHomeRouteImport } from './routes/_app/_default/home'
import { Route as AppSpacesSpaceIdRouteImport } from './routes/_app/spaces/$spaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDefaultRoute = AppDefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => AppRoute,
} as any)
const AppDefaultHomeRoute = AppDefaultHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppDefaultRoute,
} as any)
const AppSpacesSpaceIdRoute = AppSpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AppDefaultHomeRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AppDefaultHomeRoute
  '/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_default': typeof AppDefaultRouteWithChildren
  '/_app/_default/home': typeof AppDefaultHomeRoute
  '/_app/spaces/$spaceId': typeof AppSpacesSpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/spaces/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/spaces/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_default'
    | '/_app/_default/home'
    | '/_app/spaces/$spaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_default': {
      id: '/_app/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppDefaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_default/home': {
      id: '/_app/_default/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppDefaultHomeRouteImport
      parentRoute: typeof AppDefaultRoute
    }
    '/_app/spaces/$spaceId': {
      id: '/_app/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AppSpacesSpaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDefaultRouteChildren {
  AppDefaultHomeRoute: typeof AppDefaultHomeRoute
}

const AppDefaultRouteChildren: AppDefaultRouteChildren = {
  AppDefaultHomeRoute: AppDefaultHomeRoute,
}

const AppDefaultRouteWithChildren = AppDefaultRoute._addFileChildren(
  AppDefaultRouteChildren,
)

interface AppRouteChildren {
  AppDefaultRoute: typeof AppDefaultRouteWithChildren
  AppSpacesSpaceIdRoute: typeof AppSpacesSpaceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDefaultRoute: AppDefaultRouteWithChildren,
  AppSpacesSpaceIdRoute: AppSpacesSpaceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
